'''
Django settings for wallet_project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

'''

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bu8gnw#k9o@+7@&a5$l^&04a2@stxuf6j86&k5e#ay7b55ro$v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['verai.onrender.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'wallet',
    'rest_framework',
    #'myapp',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ##########################################################
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'wallet_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates/wallet', BASE_DIR, 'templates/wallet'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wallet_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

#STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
########################


PAYSTACK_SECRET_KEY = 'sk_live_af12275d942e8bb69fcc8d07863d16d4d322c08e'
PAYSTACK_PUBLIC_KEY = 'pk_live_bb9d56bc1bcae1a6466285ae297ceb8f264c6bf2'

AFRICASTALKING_API_KEY = 'your-api-key'
###########################
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# Only one definition of STATICFILES_DIRS
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'wallet\\static'),  # Ensure 'static' directory exists in the project root
    #os.path.join(BASE_DIR, 'payment_app\\static'),
]

#########

STATIC_ROOT = BASE_DIR / 'staticfiles'  # For production use, when you run `collectstatic`
#STATIC_URL = 'static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#STATICFILES_DIRS = [
#os.path.join(BASE_DIR, 'myapp\\static'),
#]

#########
###################################

AUTH_USER_MODEL = 'wallet.User'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

###################################

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'chinaecheremonwe@gmail.com'
EMAIL_HOST_PASSWORD = 'your_password'
DEFAULT_FROM_EMAIL = 'webmaster@localhost'

###########


# Stripe Payment Configurations (Example)
STRIPE_PUBLIC_KEY = 'your-stripe-public-key'
STRIPE_SECRET_KEY = 'your-stripe-secret-key'

### flutterwave###
FLW_PUBLIC_KEY = 'FLWPUBK-d12ac84bc6fbbb24ee0d39a71a5c1186-X'
FLW_SECRET_KEY = 'FLWSECK-0b02cbf325b58029cb48c9cc1cbc9c95-1971888b842vt-X'  
FLW_ENCRYPTION_KEY = '0b02cbf325b530459b19901b'

######

FLUTTERWAVE_CALLBACK_URL = 'https://verai.onrender.com/transfer-callback/'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'error_log.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

####

PAYSTACK_SECRET_KEY = os.getenv('sk_live_af12275d942e8bb69fcc8d07863d16d4d322c08e')
FLUTTERWAVE_SECRET_KEY = os.getenv('FLWSECK-0b02cbf325b58029cb48c9cc1cbc9c95-1971888b842vt-X')

#################################################
PAYMENT_HOST = 'localhost:8000'  # or your actual domain if deployed
PAYMENT_MODEL = 'payments.Payment'

AUTH_USER_MODEL = 'wallet.User'
