# Generated by Django 5.1.7 on 2025-03-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video',
            new_name='video_url',
        ),
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reel',
            field=models.FileField(blank=True, null=True, upload_to='reels/'),
        ),
    ]
